30/07/23 (20:39:32) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
04/08/23 (23:22:13) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
05/08/23 (13:15:10) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
07/08/23 (18:11:06) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
17/08/23 (11:00:02) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
17/08/23 (11:00:02) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2965, in _runner
    else: Draw.out()
  File "/usr/bin/bpytop", line 1091, in out
    cls.now(out)
  File "/usr/bin/bpytop", line 1039, in now
    print(*args, sep="", end="", flush=True)
OSError: [Errno 5] Input/output error
17/08/23 (14:00:17) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
21/08/23 (15:37:29) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
27/08/23 (17:48:37) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
01/09/23 (10:12:52) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
